version: '3'

services:
  # 1.Backend
  api:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - JUDGE0_URL=http://judge0:2358
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - judge0

  # 2.Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 3.(Judge0)
  judge0:
    image: judge0/judge0:1.13.0
    privileged: true
    ports:
      - "2358:2358"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_DB=judge0
      - JUDGE0_USE_CGROUPS=false
      - JUDGE0_RUN_IN_ISOLATED_BOX=false
      - JUDGE0_SUBMISSION_CACHE_DURATION=0
      

  # 4. Judge0's Memory 
  redis:
    image: redis:6.0
    command: [ "redis-server", "--save", "60", "1" ]

  # 5. Judge0's Logbook
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_DB=judge0
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data: